#!/bin/sh
# Combine files from within individual directories into
# a single output file.
#
# Usage:
#   combine-files <dirname> <output>
# where:
#   <dirname> - the input directory name that should be
#     matched in each <inputs>
#   <output> - the output file name
input_dir_name="$1"
output="$2"
find . -wholename "*/$input_dir_name/*" \
    -exec sh -c 'printf "# %s\n%s\n" "{}" "$(cat "{}")"' \; \
    >"$output"
