#!/bin/sh
# Stow ignores files matching patterns in .stow-local-ignore in any
# stow directory.

# We allow any directory to have a .stow-local-ignore.global - if present
# these will be propagated to the .stow-local-ignore in every directory.

# For declaring things to be ignored locally to a package, use
# .stow-local-ignore.local.

DIR="${0%/*}"

# Concatenate all .global files into one file.
stow_global_ignore_f="$(mktemp)"
"$DIR/combine-files-py" --match-file-name ".stow-local-ignore.global" "$@" > "$stow_global_ignore_f"

# Create the actual .stow-local-ignore files in each directory.
for parent_dir in "$@"; do
    cd "$parent_dir"
    for d in */; do
        cat <<EOF > "$d/.stow-local-ignore"
# global
$(cat "$stow_global_ignore_f")

# local
$([ -f "$d/.stow-local-ignore.local" ] && cat "$d/.stow-local-ignore.local")
EOF
    done
    cd - > /dev/null
done
